steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/iron-radio-450121-s8/store-registry/store-auth-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/iron-radio-450121-s8/store-registry/store-auth-ms',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
